export default Object.freeze({
  ADD_FAVORITE: 'ADD_FAVORITE',
  REMOVE_FAVORITE: 'REMOVE_FAVORITE',
  LOADING_FAVORITES: 'LOADING_FAVORITES',
  LOADING_FAVORITES_ERROR: 'LOADING_FAVORITES_ERROR',
  LOADING_SUCCESS: 'LOADING_SUCCESS',
  ADD_ERROR: 'ADD_ERROR',
  REMOVE_ERROR: 'REMOVE_ERROR',
});
