export default Object.freeze({
  SET_IS_LOADING: 'COMICS/SET_IS_LOADING',
  SET_ITEMS: 'COMICS/SET_ITEMS',
  SET_CURRENT: 'COMICS/SET_CURRENT',
  SET_REQUEST: 'COMICS/SET_REQUEST',
  SET_ERROR: 'COMICS/SET_ERROR',
  REMOVE_ERROR: 'COMICS/REMOVE_ERROR',
});
