export default Object.freeze({
  SET_IS_LOADING: 'CHARACTERS/SET_IS_LOADING',
  SET_ITEMS: 'CHARACTERS/SET_ITEMS',
  SET_CURRENT: 'CHARACTERS/SET_CURRENT',
  SET_REQUEST: 'CHARACTERS/SET_REQUEST',
  SET_ERROR: 'CHARACTERS/SET_ERROR',
  REMOVE_ERROR: 'CHARACTERS/REMOVE_ERROR',
});
